language: python
python:
  - 3.7
matrix:
  include:
  - os: linux
    dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
    sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
  - os: windows
    language: sh
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - choco install visualstudio2017-workload-vctools
    - powershell "c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - powershell cl.exe
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64"
    - ml64.exe

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run invoke -c build_tasks build-all
script:
  - pipenv run invoke test
