language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
  - pip install coveralls
  # v0.570 has a bug https://github.com/python/mypy/issues/4674 ; use 0.560 for now
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install -U mypy==0.560; fi
before_script:
  git lfs pull
# command to run tests
script:
  # Run mypy for type checking if we are on Python 3
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then python -m mypy nassl --ignore-missing-import --strict-optional; fi
  - coverage run --source=nassl setup.py test
after_success:
  coveralls
