language: python
python:
  - 3.7

matrix:
  include:
  - os: linux
    dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
    sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run invoke -c build_tasks build-all

script:
  - pipenv run invoke test
