language: python
python:
  - "2.7"
  - "3.3"
  - "3.6"
# command to install dependencies
install:
  - wget http://zlib.net/zlib-1.2.11.tar.gz
  - tar xvfz  zlib-1.2.11.tar.gz
  - git clone https://github.com/PeterMosmans/openssl.git
  - pip install -r requirements.txt --target ./lib
  - pip install coveralls
  - python build_from_scratch.py
#  - python setup.py build_ext -i
# command to run tests
script:
  coverage run --source=nassl setup.py test
after_success:
  coveralls
