language: python
python:
  - 3.7
matrix:
  include:
  - os: linux
    python: 3.7
  - os: windows
    language: sh
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
install:
  - pip install pipenv
  - pipenv install --dev
  - invoke -c build_tasks build-all
script:
  - invoke test
