image: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  #- '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Setup\WindowsSdkVer.exe" -q -version:v7.1'
  #- '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 /release'

install:
  - "%PYTHON%\\python.exe -m pip install wheel pipenv"
  - "%PYTHON%/Scripts/pipenv.exe install --dev"
  - "%PYTHON%/Scripts/pipenv.exe run invoke build.all"

test_script:
  - "%PYTHON%/Scripts/pipenv.exe run invoke test"
